#Define NodePort Service with nodePort:31001, port:8081 and targetPort:8081
apiVersion: v1
kind: Service
metadata:
  name: consumer-svc
  labels:
    app: consumer-svc
spec:
  type: NodePort
  selector:
    app: consumer-deployment
  ports:
    - nodePort: 31001
      port: 8081
      targetPort: 8081
---
#Define deployment using the image pushed to Docker Hub.
#Get environment variables from secret and name it as `RABBITMQ_USERNAME` and `RABBITMQ_PASSWORD`
#containerPort is 8081
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-deployment
  template:
    metadata:
      labels:
        app: consumer-deployment
    spec:
      containers:
        - name: consumer-app
          image: meghnanvt/consumer
          env:                        # Environment variables passed to the container
            - name: RABBITMQ_USERNAME
              valueFrom:                # Read environment variables from kubernetes secrets
                secretKeyRef:
                  name: rabbitmqsecret
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmqsecret
                  key: password
          ports:
            - containerPort: 8081

