#Define Service of type LoadBalancer with port:8080 and targetPort:9090
apiVersion: v1
kind: Service
metadata:
  name: producer-svc
  labels:
    app: producer-svc
spec:
  type: LoadBalancer
  selector:
    app: producer-deployment
  ports:
    - port: 8080
      targetPort: 9090
---
#Define deployment using the image pushed to Docker Hub.
#Get environment variables from secret and name it as `RABBITMQ_USERNAME` and `RABBITMQ_PASSWORD`
#containerPort is 9090
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-deployment
  template:
    metadata:
      labels:
        app: producer-deployment
    spec:
      containers:
        - name: producer-app
          image: meghnanvt/producerapp
          env:                        # Environment variables passed to the container
            - name: RABBITMQ_USERNAME
              valueFrom:                # Read environment variables from kubernetes secrets
                secretKeyRef:
                  name: rabbitmqsecret
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmqsecret
                  key: password
          ports:
            - containerPort: 9090

